import Dialogue from "./Entities/Dialogue";
import AEffect from  '../AEffect'

const headerTemplate = `[Script Info]\r\n\
; Script generated by AEffect\r\n\
; https://github.com/Last-Order/AEffect\r\n\
; ${new Date()}\r\n\
`;

class AssBuilder {
    /**
     * @param AEffect
     */
    static build(AEffect: AEffect){
        let ass = headerTemplate;
        for (let key of Object.keys(AEffect.styles)){
            ass += AEffect.styles[key].toString();
        }
        return ass;
    }
}


export default AssBuilder;